config/routes.rb
Callhandler::Application.routes.draw do
  devise_for :users

  resources :calls

  root :to => 'calls#index'

end

app/models/call.rb
class Call < ActiveRecord::Base
  attr_accessible :callback, :caller_email, :caller_name, :caller_number, :for_user_id, :message, :priority, :taken_by_user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  # GET /calls
  # GET /calls.json
  def index
    if params[:logged_by_me]
      @calls = Call.where(:taken_by_user_id => current_user.id)
    else
      @calls = Call.where(:for_user_id => current_user.id)
    end
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @calls }
    end
  end

  # GET /calls/1
  # GET /calls/1.json
  def show
    @call = Call.find(params[:id])
    @for_user = User.find(@call.for_user_id)
    @taken_by_user = User.find(@call.taken_by_user_id)
    @users = User.all
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @call }
    end
  end

  # GET /calls/new
  # GET /calls/new.json
  def new
    @call = Call.new
    @call.taken_by_user_id = current_user.id
    @users = User.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @call }
    end
  end

  # GET /calls/1/edit
  def edit
    @call = Call.find(params[:id])
    @users = User.all
  end

  # POST /calls
  # POST /calls.json
  def create
    @call = Call.new(params[:call])

    respond_to do |format|
      if @call.save
        format.html { redirect_to @call, notice: 'Call was successfully created.' }
        format.json { render json: @call, status: :created, location: @call }
      else
        format.html { render action: "new" }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /calls/1
  # PUT /calls/1.json
  def update
    @call = Call.find(params[:id])

    respond_to do |format|
      if @call.update_attributes(params[:call])
        format.html { redirect_to @call, notice: 'Call was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.json
  def destroy
    @call = Call.find(params[:id])
    @call.destroy

    respond_to do |format|
      format.html { redirect_to calls_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_form.html.haml
= form_for @call, :html => { :class => "form-horizontal"} do |f|
  - if @call.errors.any?
    #error_explanation
      %h2
        = pluralize(@call.errors.count, "error")
        prohibited this call from being saved:

      %ul
      - @call.errors.full_messages.each do |msg|
        %li
          = msg

  .control-group
    = f.label :caller_name, :class => "control-label"
    .controls
      = f.text_field :caller_name, :required => true
  .control-group
    = f.label :caller_number, :class => "control-label"
    .controls
      = f.text_field :caller_number
  .control-group
    = f.label :caller_email, :class => "control-label"
    .controls
      = f.text_field :caller_email
  .control-group
    = f.label :message, :class => "control-label"
    .controls
      = f.text_area :message
  .control-group
    = f.label :priority, :class => "control-label"
    .controls
      = f.select :priority, PRIORITIES, :include_blank => false
  .control-group
    = f.label "Callback?", :class => "control-label"
    .controls
      = f.check_box :callback
  .control-group
    = f.label :for_user_id, :class => "control-label"
    .controls
      = f.select(:for_user_id, options_from_collection_for_select(@users, "id", "email", @call.for_user_id))
  .control-group
    = f.label :taken_by_user_id, :class => "control-label"
    .controls
      = f.select(:taken_by_user_id, options_from_collection_for_select(@users, "id", "email", @call.taken_by_user_id)) 
  .actions
    = f.submit

app/views/calls/_index.html.haml
%table.table.table-striped
  %tr
    %th Call Date
    %th Caller name
    %th Caller number
    %th Caller email
    %th Priority
    %th Callback
    %th For user
    %th Taken by user
    %th
    %th
    %th

  - @calls.each do |call|
    %tr
      %td
        = call.created_at
      %td
        = call.caller_name
      %td
        = call.caller_number
      %td
        = call.caller_email
      %td{:class => "priority_#{call.priority}" }
        = PRIORITIES[call.priority][0]
      %td
        = YESNO[call.callback.to_i]
      %td
        = @users.find(call.for_user_id).first.email.split('@').first
      %td
        = @users.find(call.taken_by_user_id).first.email.split('@').first
      %td
        = link_to 'Show', call
      %td
        = link_to 'Edit', edit_call_path(call)
      %td
        = link_to 'Destroy', call, method: :delete, data: { confirm: 'Are you sure?' }

app/views/calls/edit.html.haml
%h3
  = @pagetitle

= render 'form'

app/views/calls/index.html.haml
%h3
  = @pagetitle

= render 'index'

app/views/calls/new.html.haml
%h3
  New call

= render 'form'

app/views/calls/show.html.haml
%p{:id => "notice"}
  = notice

%p
  %b
    Caller name:
  = @call.caller_name
%p
  %b
    Caller number:
  = @call.caller_number
%p
  %b
    Caller email:
  = @call.caller_email
%p
  %b
    Message:
  = @call.message
%p
  %b
    Priority:
  = PRIORITIES[@call.priority][0]
%p
  %b
    Callback:
  = YESNO[@call.callback.to_i]
%p
  %b
    For user:
  = @for_user.email.split('@').first
%p
  %b
    Taken by user:
  = @taken_by_user.email.split('@').first

= link_to 'Edit', edit_call_path(@call)
|
= link_to 'Back', calls_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Call Handler Helper</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#">Call Handler Helper</a>
 
      <ul class="nav">
        <% if user_signed_in? %>
          <li>
            <%= link_to('Calls for me', root_path) %>
          </li>
          <li>
            <%= link_to 'Calls logged by me', root_path(:logged_by_me => true) %>
          </li>
          <li>
            <%= link_to 'New Call', new_call_path %>
          </li>
          <li>
          <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
          </li>
          <li>
          <%= link_to('Edit account', edit_user_registration_path) %>
          </li>
        <% else %>
          <li>
          <%= link_to('Login', new_user_session_path)  %>  
          </li>
          <li>
          <%= link_to('Sign up', new_user_registration_path)  %>
          </li>
        <% end %>
      </ul>

      <% if user_signed_in? %>
        <img src="https://secure.gravatar.com/avatar/<%= Digest::MD5.hexdigest(current_user.email) %>?s=30" />
      <% end %>

      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
      </div>
 
    </div>
  </div>
</div>
<div class="container">

<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

<%= yield %>
</div>
</body>
</html>